steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gsutil'
    args: ['cp', 'gs://${_BUCKET_NAME}/key.json', '.']
    id: Init
  - name: 'python:3.9-slim'
    entrypoint: /bin/sh
    args:
      - -c
      - 'pip install flask firebase_admin && python test_app.py -v'
    id: Test
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA'
    id: Push

  